### PR TITLE
Add logic fo fetching and setting user avatars.

### PR DESCRIPTION
**Pull request by nihilus**
Add logic fo fetching and setting user avatars.

### CODE REVIEW

**Comment by EionRobb** [comment]
That code looks familiar 😉

**Comment by EionRobb** [comment]
You'll want to add in a define for g-timeout-add to map to purple-timeout-add for purple2 since it does its own event loop, but purple3 just uses the glib loop

**Comment by nihilus** [comment]
@EionRobb yeah, I should have said I stole the front-end part from skypeweb.

**Comment by nihilus** [comment]
./purple_compat.h:#define g_timeout_add_seconds  purple_timeout_add_seconds
./purple_compat.h:#define g_timeout_add          purple_timeout_add

**Comment by hoehermann** [comment]
That's a lot of code. Thank you. It will take a while until I can read it all.

@EionRobb You put effort in supporting libpurple 3. I am not doing so when writing these plug-ins. Is there a front-end which uses libpurple 3?

**Comment by nihilus** [comment]
Most of it is just a copy of the purple2compat-folder from the skypeweb, needed for the http-requests from the front-end.

**Comment by hoehermann** [comment]
I see. It is quite verbose on the C-side. I'd probably have done the download in go and then forwarded the binary data, but that is regarded as unclean and not libpurp-ly. Your way is probably better.

**Comment by nihilus** [comment]
> I see. It is quite verbose on the C-side. I'd probably have done the download in go and then forwarded the binary data, but that is regarded as unclean and not libpurp-ly. Your way is probably better.

I was considering using http.get from golang, but I prefer not to handle the image in golang and then send a blob to the front-end since it would add complexity; given that @EionRobb already implemented the fetch-logic in skypeweb (which is pretty well tested and known to work).

**Comment by EionRobb** [comment]
> @EionRobb You put effort in supporting libpurple 3. I am not doing so when writing these plug-ins since I am not using any appropriate software. Is there any front-end which uses libpurple 3?

Yes, Pidgin 3 uses libpurple 3

**Comment by hoehermann** [comment]
I did not even now that existed. :o Thank you. One day, I probably want to build it and adjust the plug-in to work with it. :)

**Comment by nihilus** [comment]
Yes, Plugin 3 is the mercurial trunk branch; however it is not afaik near ready for a release. After 2 years we are still waiting for the 2.14.0 release, which brings some nice bug fixes.

I can try to strip out the unneeded functionality from purple2compat and rebase.

**Comment by hoehermann** [comment]
No, just leave it in. Supporting libpurple 3 does not sound like a bad idea – I just did not know what it was for.

**Comment by hoehermann** [comment]
I have not forgotten about this one. But I have been doing a lot of code reviews at my day job and therefore I am not keen on more code reviews in my free time. Please bear with me.

**Comment by hoehermann** [comment]
Something in there is blocking. I suspect it is `gowhatsapp_get_icon_url`. The UI locks up and stutters. For this reason, the feature is user-configurable, but default off.

**Comment by nihilus** [comment]
@hoerhermann yes, I can confirm that

**Pull request merged**
